#!/usr/bin/env bash

################################################################################
# Build TensorRT INT8 Engine for Jetson Orin Deployment
#
# This script converts an ONNX model to a TensorRT INT8 engine optimized
# for the target Jetson hardware. It MUST be run on the target device
# (Jetson Orin NX / AGX Orin) for proper kernel auto-tuning.
#
# Prerequisites:
#   - TensorRT installed (comes with JetPack)
#   - Calibration frames generated by generate_int8_calibration.py
#   - ONNX model file
#
# Usage:
#   ./build_int8_engine.sh [OPTIONS]
#
# Examples:
#   # Default (GELAN-C 640x640, INT8+FP16 mixed precision)
#   ./build_int8_engine.sh
#
#   # Custom model
#   ./build_int8_engine.sh --onnx path/to/model.onnx --batch 8
#
#   # FP16 only (no calibration needed)
#   ./build_int8_engine.sh --fp16-only
################################################################################

set -euo pipefail

# ─── Defaults ────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
MODEL_DIR="${REPO_ROOT}/python_test/deepstream-test-sahi/models"

ONNX_FILE="${MODEL_DIR}/gelan-c-visdrone-full-frame-640-end2end.onnx"
CALIB_DIR="${MODEL_DIR}/calibration"
CALIB_LIST="${CALIB_DIR}/calibration_list.txt"
CALIB_CACHE="${MODEL_DIR}/int8_calibration.cache"

BATCH_SIZE=8
WORKSPACE_MB=4096
INPUT_SIZE=640
FP16_ONLY=false
VERBOSE=false

# ─── Parse Arguments ────────────────────────────────────────────────────────

usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Options:
  --onnx PATH         Path to ONNX model (default: gelan-c-visdrone-full-frame-640-end2end.onnx)
  --batch N           Batch size for engine (default: 8)
  --workspace MB      TensorRT workspace in MB (default: 4096)
  --calib-dir PATH    Calibration frames directory (default: models/calibration/)
  --calib-cache PATH  Calibration cache file (default: models/int8_calibration.cache)
  --fp16-only         Build FP16 engine only (no INT8, no calibration needed)
  --verbose           Enable verbose TensorRT logging
  -h, --help          Show this help message

Examples:
  # Build INT8 engine (default settings)
  $(basename "$0")

  # Build FP16-only engine
  $(basename "$0") --fp16-only

  # Custom model with batch=4
  $(basename "$0") --onnx my_model.onnx --batch 4
EOF
    exit 0
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --onnx)       ONNX_FILE="$2"; shift 2 ;;
        --batch)      BATCH_SIZE="$2"; shift 2 ;;
        --workspace)  WORKSPACE_MB="$2"; shift 2 ;;
        --calib-dir)  CALIB_DIR="$2"; shift 2 ;;
        --calib-cache) CALIB_CACHE="$2"; shift 2 ;;
        --fp16-only)  FP16_ONLY=true; shift ;;
        --verbose)    VERBOSE=true; shift ;;
        -h|--help)    usage ;;
        *)
            echo "Unknown option: $1" >&2
            usage
            ;;
    esac
done

# ─── Validate ────────────────────────────────────────────────────────────────

if [[ ! -f "${ONNX_FILE}" ]]; then
    echo "ERROR: ONNX model not found: ${ONNX_FILE}" >&2
    exit 1
fi

TRTEXEC="$(command -v trtexec 2>/dev/null || echo "/usr/src/tensorrt/bin/trtexec")"
if [[ ! -x "${TRTEXEC}" ]]; then
    echo "ERROR: trtexec not found. Ensure TensorRT is installed (JetPack)." >&2
    echo "       Expected at: /usr/src/tensorrt/bin/trtexec" >&2
    exit 1
fi

# ─── Determine output engine name ────────────────────────────────────────────

ONNX_BASENAME="$(basename "${ONNX_FILE}" .onnx)"

# Detect GPU info for engine naming
GPU_NAME="$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 | tr ' ' '_' | tr -d '()' || echo "unknown_gpu")"
COMPUTE_CAP="$(nvidia-smi --query-gpu=compute_cap --format=csv,noheader 2>/dev/null | head -1 | tr -d '.' || echo "00")"
TRT_VER="$(${TRTEXEC} --help 2>&1 | head -1 | grep -oP 'TensorRT v\K[0-9.]+' | tr -d '.' | cut -c1-4 || echo "0000")"

if [[ "${FP16_ONLY}" == "true" ]]; then
    PRECISION="fp16"
else
    PRECISION="int8"
fi

ENGINE_NAME="${ONNX_BASENAME}_b${BATCH_SIZE}_i${INPUT_SIZE}x${INPUT_SIZE}_sm${COMPUTE_CAP}_${GPU_NAME}_trt${TRT_VER}_${PRECISION}.engine"
ENGINE_FILE="${MODEL_DIR}/${ENGINE_NAME}"

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║           TensorRT Engine Builder — Drone Deployment           ║"
echo "╠══════════════════════════════════════════════════════════════════╣"
echo "║ ONNX model : $(basename "${ONNX_FILE}")"
echo "║ Precision  : ${PRECISION}"
echo "║ Batch size : ${BATCH_SIZE}"
echo "║ Input size : ${INPUT_SIZE}x${INPUT_SIZE}"
echo "║ Workspace  : ${WORKSPACE_MB} MB"
echo "║ GPU        : ${GPU_NAME} (sm_${COMPUTE_CAP})"
echo "║ Output     : ${ENGINE_NAME}"
echo "╚══════════════════════════════════════════════════════════════════╝"

# ─── Build Command ───────────────────────────────────────────────────────────

CMD=("${TRTEXEC}")
CMD+=("--onnx=${ONNX_FILE}")
CMD+=("--saveEngine=${ENGINE_FILE}")
CMD+=("--workspace=${WORKSPACE_MB}")

if [[ "${FP16_ONLY}" == "true" ]]; then
    CMD+=("--fp16")
    echo ""
    echo "Building FP16 engine (no calibration needed)..."
else
    # INT8 + FP16 mixed precision
    CMD+=("--int8")
    CMD+=("--fp16")

    if [[ -f "${CALIB_CACHE}" ]]; then
        echo ""
        echo "Using existing calibration cache: ${CALIB_CACHE}"
        CMD+=("--calib=${CALIB_CACHE}")
    elif [[ -f "${CALIB_LIST}" ]]; then
        echo ""
        echo "Calibration cache not found. Running calibration from: ${CALIB_DIR}"
        echo "This may take several minutes..."
        CMD+=("--calib=${CALIB_CACHE}")
        # TensorRT will generate the cache from the calibration data
    else
        echo ""
        echo "ERROR: No calibration data found." >&2
        echo "       Run scripts/generate_int8_calibration.py first." >&2
        echo "       Expected: ${CALIB_LIST}" >&2
        exit 1
    fi
fi

if [[ "${VERBOSE}" == "true" ]]; then
    CMD+=("--verbose")
fi

echo ""
echo "Command: ${CMD[*]}"
echo ""
echo "Building engine (this may take 5-30 minutes on Jetson)..."
echo "────────────────────────────────────────────────────────"

time "${CMD[@]}"

echo ""
echo "════════════════════════════════════════════════════════"
echo "Engine built successfully: ${ENGINE_FILE}"
echo "Engine size: $(du -h "${ENGINE_FILE}" | cut -f1)"
echo ""
echo "To use in DeepStream, set in your pgie config:"
echo "  model-engine-file=${ENGINE_FILE}"
echo "════════════════════════════════════════════════════════"
